<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mime-info [
  <!ELEMENT mime-info (mime-type)+>
  <!ATTLIST mime-info xmlns CDATA #FIXED "http://www.freedesktop.org/standards/shared-mime-info">

  <!ELEMENT mime-type (comment|glob|magic|root-XML|alias|sub-class-of)*>
  <!ATTLIST mime-type type CDATA #REQUIRED>

  <!ELEMENT comment (#PCDATA)>

  <!ELEMENT glob EMPTY>
  <!ATTLIST glob pattern CDATA #REQUIRED>

  <!ELEMENT magic (match)+>
  <!ATTLIST magic priority CDATA #IMPLIED>

  <!ELEMENT match (match)*>
  <!ATTLIST match offset CDATA #REQUIRED>
  <!ATTLIST match type (string|big16|big32|little16|little32|host16|host32|byte) #REQUIRED>
  <!ATTLIST match value CDATA #REQUIRED>
  <!ATTLIST match mask CDATA #IMPLIED>

  <!ELEMENT root-XML EMPTY>
  <!ATTLIST root-XML
  	namespaceURI CDATA #REQUIRED
	localName CDATA #REQUIRED>

  <!ELEMENT alias EMPTY>
  <!ATTLIST alias
  	type CDATA #REQUIRED>

  <!ELEMENT sub-class-of EMPTY>
  <!ATTLIST sub-class-of
  	type CDATA #REQUIRED>
]>

<!-- 
The freedesktop.org shared MIME database (this file) was created by merging
several existing MIME databases (all released under the GPL).

It comes with ABSOLUTELY NO WARRANTY, to the extent permitted by law. You may
redistribute copies of update-mime-database under the terms of the GNU General
Public License. For more information about these matters, see the file named
COPYING.

The latest version is available from:

	http://www.freedesktop.org/standards/shared-mime-info.html

To extend this database, users and applications should create additional
XML files in the 'packages' directory and run the update-mime-database
command to generate the output files.
-->

<mime-info xmlns="http://www.freedesktop.org/standards/shared-mime-info">
  <mime-type type="application/andrew-inset">
    <comment>Andrew Toolkit inset</comment>
    <comment xml:lang="hu">Andrew Toolkit inset</comment>
    <comment xml:lang="sr">Andrew додатаг групе алата</comment>
    <glob pattern="*.ez"/>
  </mime-type>
  <mime-type type="application/illustrator">
    <comment>Adobe Illustrator Document</comment>
    <comment xml:lang="hu">Adobe Illustrator-dokumentum</comment>
    <comment xml:lang="sr">Adobe Illustrator документ</comment>
    <glob pattern="*.ai"/>
  </mime-type>
  <mime-type type="application/mac-binhex40">
    <comment>Macintosh BinHex-encoded file</comment>
    <comment xml:lang="hu">Macintosh BinHex kódolású fájl</comment>
    <comment xml:lang="sr">Мекинтош BinHex-encoded датотека</comment>
    <magic priority="50">
      <match type="string" value="must be converted with BinHex" offset="11"/>
    </magic>
  </mime-type>
  <mime-type type="application/msword">
    <comment>Microsoft Word document</comment>
    <comment xml:lang="hu">Microsoft Word-dokumentum</comment>
    <comment xml:lang="sr">Микрософт Word документ</comment>
    <magic priority="50">
      <match type="string" value="\x31\xbe\x00\x00" offset="0"/>
      <match type="string" value="PO^Q`" offset="0"/>
      <match type="string" value="\376\067\0\043" offset="0"/>
      <match type="string" value="\320\317\021\340\241\261" offset="0"/>
      <match type="string" value="\333\245-\0\0\0" offset="0"/>
      <match type="string" value="Microsoft Word 6.0 Document" offset="2080"/>
      <match type="string" value="Microsoft Word document data" offset="2112"/>
    </magic>
    <glob pattern="*.doc"/>
  </mime-type>
  <mime-type type="application/octet-stream">
    <comment>Unknown</comment>
    <comment xml:lang="hu">Ismeretlen</comment>
    <comment xml:lang="sr">Непознато</comment>
    <magic priority="50">
      <match type="string" value="\037\036" offset="0"/>
      <match type="host16" value="017437" offset="0"/>
      <match type="host16" value="0x1fff" offset="0"/>
      <match type="string" value="\377\037" offset="0"/>
      <match type="host16" value="0145405" offset="0"/>
    </magic>
    <glob pattern="*.bin"/>
  </mime-type>
  <mime-type type="application/oda">
    <comment>ODA document</comment>
    <comment xml:lang="hu">ODA-dokumentum</comment>
    <comment xml:lang="sr">ODA документ</comment>
    <glob pattern="*.oda"/>
  </mime-type>
  <mime-type type="application/pdf">
    <comment>Pdf Document</comment>
    <comment xml:lang="sr">ПДФ документ</comment>
    <magic priority="50">
      <match type="string" value="%PDF-" offset="0"/>
    </magic>
    <glob pattern="*.pdf"/>
  </mime-type>
  <mime-type type="application/pgp">
    <comment>PGP message</comment>
    <comment xml:lang="hu">PGP-üzenet</comment>
    <comment xml:lang="sr">PGP порука</comment>
    <glob pattern="*.pgp"/>
  </mime-type>
  <mime-type type="application/pgp-encrypted">
    <comment>PGP/MIME encrypted message header</comment>
    <comment xml:lang="sr">ПГП/МИМЕ шифрована порука</comment>
  </mime-type>
  <mime-type type="application/pgp-keys">
    <comment>PGP keys</comment>
    <comment xml:lang="hu">PGP-kulcs</comment>
    <comment xml:lang="sr">PGP кључ</comment>
  </mime-type>
  <mime-type type="application/pgp-signature">
    <comment>Detached OpenPGP signature</comment>
    <comment xml:lang="sr">Одвојени ОпенПГП потпис</comment>
  </mime-type>
  <mime-type type="application/pkcs7-mime">
    <comment>S/MIME file</comment>
    <comment xml:lang="hu">S/MIME-fájl</comment>
    <comment xml:lang="sr">S/MIME датотека</comment>
  </mime-type>
  <mime-type type="application/pkcs7-signature">
    <comment>Detached S/MIME signature</comment>
    <comment xml:lang="sr">Одвојени S/MIME потпис</comment>
    <glob pattern="*.p7s"/>
  </mime-type>
  <mime-type type="application/postscript">
    <comment>PostScript Document</comment>
    <comment xml:lang="sr">ПостСкрипт документ</comment>
    <magic priority="50">
      <match type="string" value="\004%!" offset="0"/>
      <match type="string" value="%!" offset="0"/>
    </magic>
    <glob pattern="*.ps"/>
  </mime-type>
  <mime-type type="application/rtf">
    <comment>Rich Text Format</comment>
    <comment xml:lang="sr">Обогаћени текстуални запис (RTF)</comment>
    <magic priority="50">
      <match type="string" value="{\\rtf" offset="0"/>
    </magic>
    <glob pattern="*.rtf"/>
  </mime-type>
  <mime-type type="application/smil">
    <comment>Synchronized Multimedia Integration Language</comment>
    <comment xml:lang="sr">Синхронизовани језик за интеграцију мултимедије (SMIL)</comment>
    <glob pattern="*.smil"/>
    <glob pattern="*.smi"/>
    <glob pattern="*.sml"/>
  </mime-type>
  <mime-type type="application/vnd.corel-draw">
    <comment>Corel Draw drawing</comment>
    <comment xml:lang="hu">Corel Draw-rajz</comment>
    <comment xml:lang="sr">Corel Draw цртеж</comment>
    <magic priority="50">
      <match type="string" value="CDR vrsn" offset="8"/>
    </magic>
    <glob pattern="*.cdr"/>
  </mime-type>
  <mime-type type="application/vnd.lotus-1-2-3">
    <comment>Lotus 1-2-3 spreadsheet</comment>
    <comment xml:lang="hu">Lotus 1-2-3-munkafüzet</comment>
    <comment xml:lang="sr">Lotus 1-2-3 табеларни прорачун</comment>
    <magic priority="50">
      <match type="string" value="\x00\x00\x02\x00" offset="0"/>
    </magic>
    <glob pattern="*.123"/>
    <glob pattern="*.wk1"/>
    <glob pattern="*.wk3"/>
    <glob pattern="*.wk4"/>
    <glob pattern="*.wks"/>
  </mime-type>
  <mime-type type="application/vnd.ms-excel">
    <comment>Microsoft Excel spreadsheet</comment>
    <comment xml:lang="hu">Microsoft Excel-munkafüzet</comment>
    <comment xml:lang="sr">Микрософт Ексел табеларни прорачун</comment>
    <magic priority="50">
      <match type="string" value="Microsoft Excel 5.0 Worksheet" offset="2080"/>
    </magic>
    <glob pattern="*.xls"/>
    <glob pattern="*.xlc"/>
    <glob pattern="*.xll"/>
    <glob pattern="*.xlm"/>
    <glob pattern="*.xlw"/>
    <glob pattern="*.xla"/>
    <glob pattern="*.xlt"/>
    <glob pattern="*.xld"/>
  </mime-type>
  <mime-type type="application/vnd.ms-powerpoint">
    <comment>Microsoft PowerPoint document</comment>
    <comment xml:lang="hu">Microsoft PowerPoint-dokumentum</comment>
    <comment xml:lang="sr">Микрософт ПауерПоинт документ</comment>
    <glob pattern="*.ppz"/>
    <glob pattern="*.ppt"/>
    <glob pattern="*.pps"/>
    <glob pattern="*.pot"/>
  </mime-type>
  <mime-type type="application/vnd.ms-word">
    <comment>Microsoft Word document</comment>
    <comment xml:lang="hu">Microsoft Word-dokumentum</comment>
    <comment xml:lang="sr">Микрософт Word документ</comment>
  </mime-type>
  <mime-type type="application/vnd.rn-realmedia">
    <comment>RealAudio/Video document</comment>
    <comment xml:lang="hu">RealAudio/Video-dokumentum</comment>
    <comment xml:lang="sr">RealAudio/Video документ</comment>
  </mime-type>
  <mime-type type="application/vnd.stardivision.calc">
    <comment>StarCalc spreadsheet</comment>
    <comment xml:lang="hu">StarCalc-munkafüzet</comment>
    <comment xml:lang="sr">StarCalc табеларни прорачун</comment>
    <glob pattern="*.sdc"/>
  </mime-type>
  <mime-type type="application/vnd.stardivision.chart">
    <comment>StarChart chart</comment>
    <comment xml:lang="hu">StarChart-grafikon</comment>
    <comment xml:lang="sr">StarChart графикон</comment>
    <glob pattern="*.sds"/>
  </mime-type>
  <mime-type type="application/vnd.stardivision.draw">
    <comment>StarDraw drawing</comment>
    <comment xml:lang="hu">StarDraw-rajz</comment>
    <comment xml:lang="sr">StarDraw drawing</comment>
    <glob pattern="*.sda"/>
  </mime-type>
  <mime-type type="application/vnd.stardivision.impress">
    <comment>StarImpress presentation</comment>
    <comment xml:lang="hu">StarImpress-bemutató</comment>
    <comment xml:lang="sr">StarImpress презентација</comment>
    <glob pattern="*.sdd"/>
    <glob pattern="*.sdp"/>
  </mime-type>
  <mime-type type="application/vnd.stardivision.mail">
    <comment>StarMail file</comment>
    <comment xml:lang="hu">StarMail-fájl</comment>
    <comment xml:lang="sr">StarMail датотека</comment>
    <glob pattern="*.smd"/>
  </mime-type>
  <mime-type type="application/vnd.stardivision.math">
    <comment>StarMath document</comment>
    <comment xml:lang="hu">StarMath-dokumentum</comment>
    <comment xml:lang="sr">StarMath документ</comment>
    <glob pattern="*.smf"/>
  </mime-type>
  <mime-type type="application/vnd.stardivision.writer">
    <comment>StarWriter document</comment>
    <comment xml:lang="hu">StarWriter-dokumentum</comment>
    <comment xml:lang="sr">StarWriter документ</comment>
    <glob pattern="*.sdw"/>
    <glob pattern="*.vor"/>
    <glob pattern="*.sgl"/>
  </mime-type>
  <mime-type type="application/vnd.sun.xml.calc">
    <comment>OpenOffice spreadsheet</comment>
    <comment xml:lang="sr">OpenOffice табеларни рачун</comment>
    <glob pattern="*.sxc"/>
  </mime-type>
  <mime-type type="application/vnd.sun.xml.calc.template">
    <comment>OpenOffice spreadsheet template</comment>
    <comment xml:lang="sr">OpenOffice шаблон табеларног прорачуна</comment>
    <glob pattern="*.stc"/>
  </mime-type>
  <mime-type type="application/vnd.sun.xml.draw">
    <comment>OpenOffice drawing</comment>
    <comment xml:lang="sr">OpenOffice цртеж</comment>
    <glob pattern="*.sxd"/>
  </mime-type>
  <mime-type type="application/vnd.sun.xml.draw.template">
    <comment>OpenOffice drawing template</comment>
    <comment xml:lang="sr">OpenOffice шаблон цртежа</comment>
    <glob pattern="*.std"/>
  </mime-type>
  <mime-type type="application/vnd.sun.xml.impress">
    <comment>OpenOffice Impress presentation</comment>
    <comment xml:lang="sr">OpenOffice Impress презентација</comment>
    <glob pattern="*.sxi"/>
  </mime-type>
  <mime-type type="application/vnd.sun.xml.impress.template">
    <comment>OpenOffice Impress presentation template</comment>
    <comment xml:lang="sr">OpenOffice Impress шаблон презентације</comment>
    <glob pattern="*.sti"/>
  </mime-type>
  <mime-type type="application/vnd.sun.xml.math">
    <comment>OpenOffice Math document</comment>
    <comment xml:lang="sr">OpenOffice Math документ</comment>
    <glob pattern="*.sxm"/>
  </mime-type>
  <mime-type type="application/vnd.sun.xml.writer">
    <comment>OpenOffice Writer document</comment>
    <comment xml:lang="sr">OpenOffice Writer документ</comment>
    <glob pattern="*.sxw"/>
  </mime-type>
  <mime-type type="application/vnd.sun.xml.writer.global">
    <comment>OpenOffice Writer global document</comment>
    <comment xml:lang="sr">OpenOffice Writer глобални документ</comment>
    <glob pattern="*.sxg"/>
  </mime-type>
  <mime-type type="application/vnd.sun.xml.writer.template">
    <comment>OpenOffice Writer template</comment>
    <comment xml:lang="sr">OpenOffice Writer шаблон</comment>
    <glob pattern="*.stw"/>
  </mime-type>
  <mime-type type="application/wordperfect">
    <comment>WordPerfect document</comment>
    <comment xml:lang="hu">WordPerfect-dokumentum</comment>
    <comment xml:lang="sr">WordPerfect документ</comment>
    <magic priority="50">
      <match type="string" value="WPC" offset="1"/>
      <!-- <match type="big32" value="0xff575053c405" offset="0"/> -->
    </magic>
    <glob pattern="*.wpd"/>
  </mime-type>
  <mime-type type="application/xbell">
    <comment>XBEL bookmarks file</comment>
    <comment xml:lang="hu">XBEL-könyvjelzőfájl</comment>
    <comment xml:lang="sr">XBEL датотека маркера</comment>
    <magic priority="50">
      <match type="string" value="&lt;!DOCTYPE\ xbel" offset="0:64"/>
    </magic>
    <glob pattern="*.xbel"/>
  </mime-type>
  <mime-type type="application/x-abiword">
    <comment>AbiWord Document</comment>
    <comment xml:lang="hu">AbiWord-dokumentum</comment>
    <comment xml:lang="sr">AbiWord документ</comment>
    <magic priority="50">
      <match type="string" value="&lt;abiword" offset="0:64"/>
      <match type="string" value="&lt;!DOCTYPE abiword" offset="0:64"/>
    </magic>
    <glob pattern="*.abw"/>
    <glob pattern="*.abw.gz"/>
    <glob pattern="*.zabw"/>
  </mime-type>
  <mime-type type="application/x-amipro">
    <comment>Lotus AmiPro document</comment>
    <comment xml:lang="hu">Lotus AmiPro-dokumentum</comment>
    <comment xml:lang="sr">Лотус АмиПро документ</comment>
    <glob pattern="*.sam"/>
  </mime-type>
  <mime-type type="application/x-applix-spreadsheet">
    <comment>Applix Spreadsheets document</comment>
    <comment xml:lang="sr">Applix Spreadsheets документ</comment>
    <magic priority="50">
      <match type="string" value="*BEGIN SPREADSHEETS" offset="0"/>
      <match type="string" value="*BEGIN" offset="0">
        <match type="string" value="SPREADSHEETS" offset="7"/>
      </match>
    </magic>
    <glob pattern="*.as"/>
  </mime-type>
  <mime-type type="application/x-applix-word">
    <comment>Applix Words document</comment>
    <comment xml:lang="sr">Applix Words документ</comment>
    <magic priority="50">
      <match type="string" value="*BEGIN" offset="0">
        <match type="string" value="WORDS" offset="7"/>
      </match>
    </magic>
    <glob pattern="*.aw"/>
  </mime-type>
  <mime-type type="application/x-arc">
    <magic priority="50">
      <match type="little32" mask="0x8080ffff" value="0x0000081a" offset="0"/>
      <match type="little32" mask="0x8080ffff" value="0x0000091a" offset="0"/>
      <match type="little32" mask="0x8080ffff" value="0x0000021a" offset="0"/>
      <match type="little32" mask="0x8080ffff" value="0x0000031a" offset="0"/>
      <match type="little32" mask="0x8080ffff" value="0x0000041a" offset="0"/>
      <match type="little32" mask="0x8080ffff" value="0x0000061a" offset="0"/>
    </magic>
  </mime-type>
  <mime-type type="application/x-archive">
    <comment>Ar Archives</comment>
    <comment xml:lang="hu">Ar-archívum</comment>
    <comment xml:lang="sr">Ar архива</comment>
    <magic priority="50">
      <match type="string" value="&lt;ar&gt;" offset="0"/>
      <match type="string" value="!&lt;arch&gt;" offset="0"/>
    </magic>
    <glob pattern="*.a"/>
  </mime-type>
  <mime-type type="application/x-arj">
    <comment>ARJ archive</comment>
    <comment xml:lang="hu">ARJ-archívum</comment>
    <comment xml:lang="sr">ARJ архива</comment>
    <magic priority="50">
      <match type="little16" value="0xea60" offset="0"/>
    </magic>
    <glob pattern="*.arj"/>
  </mime-type>
  <mime-type type="application/x-asp">
    <comment>active server page</comment>
    <comment xml:lang="sr">Активна серверска страна</comment>
    <glob pattern="*.asp"/>
  </mime-type>
  <mime-type type="application/x-awk">
    <comment>AWK script</comment>
    <comment xml:lang="hu">AWK-szkript</comment>
    <comment xml:lang="sr">AWK скрипта</comment>
    <magic priority="50">
      <match type="string" value="#!/bin/gawk" offset="0"/>
      <match type="string" value="#! /bin/gawk" offset="0"/>
      <match type="string" value="#!/usr/bin/gawk" offset="0"/>
      <match type="string" value="#! /usr/bin/gawk" offset="0"/>
      <match type="string" value="#!/usr/local/bin/gawk" offset="0"/>
      <match type="string" value="#! /usr/local/bin/gawk" offset="0"/>
      <match type="string" value="#!/bin/awk" offset="0"/>
      <match type="string" value="#! /bin/awk" offset="0"/>
      <match type="string" value="#!/usr/bin/awk" offset="0"/>
      <match type="string" value="#! /usr/bin/awk" offset="0"/>
    </magic>
  </mime-type>
  <mime-type type="application/x-bcpio">
    <comment>BCPIO document</comment>
    <comment xml:lang="hu">BCPIO-dokumentum</comment>
    <comment xml:lang="sr">BCPIO документ</comment>
    <glob pattern="*.bcpio"/>
  </mime-type>
  <mime-type type="application/x-bittorrent">
    <comment>BitTorrent seed file</comment>
    <comment xml:lang="sr">Датотека са БитТорентовим полазиштима</comment>
    <magic priority="50">
      <match type="string" value="d8:announce" offset="0"/>
    </magic>
    <glob pattern="*.torrent"/>
  </mime-type>
  <mime-type type="application/x-blender">
    <comment>Blender file</comment>
    <comment xml:lang="hu">Blender-fájl</comment>
    <comment xml:lang="sr">Блендер датотека</comment>
    <glob pattern="*.blender"/>
    <glob pattern="*.blend"/>
    <glob pattern="*.BLEND"/>
    <magic priority="50">
      <match type="string" value="BLENDER" offset="0"/>
    </magic>
  </mime-type>
  <mime-type type="application/x-bzip">
    <comment>Bzip file</comment>
    <comment xml:lang="hu">Bzip-fájl</comment>
    <comment xml:lang="sr">Bzip датотека</comment>
    <magic priority="50">
      <match type="string" value="BZh" offset="0"/>
    </magic>
    <glob pattern="*.bz"/>
    <glob pattern="*.bz2"/>
  </mime-type>
  <mime-type type="application/x-bzip-compressed-tar">
    <comment>Bzipped Tar Archives</comment>
    <comment xml:lang="sr">Бзипована ТАР архива</comment>
    <glob pattern="*.tar.bz"/>
    <glob pattern="*.tar.bz2"/>
  </mime-type>
  <mime-type type="application/x-cd-image">
    <comment>Raw CD image</comment>
    <comment xml:lang="sr">Сирови отисак ЦД-а</comment>
    <glob pattern="*.iso"/>
  </mime-type>
  <mime-type type="application/x-cgi">
    <comment>CGI program</comment>
    <comment xml:lang="hu">CGI-program</comment>
    <comment xml:lang="sr">CGI програм</comment>
    <glob pattern="*.cgi"/>
  </mime-type>
  <mime-type type="application/x-chess-pgn">
    <comment>PGN chess game</comment>
    <comment xml:lang="hu">PGN-sakkjátszma</comment>
    <comment xml:lang="sr">PGN шаховска игра</comment>
    <glob pattern="*.pgn"/>
  </mime-type>
  <mime-type type="application/x-class-file">
    <comment>Java byte code</comment>
    <comment xml:lang="hu">Java-bájtkód</comment>
    <comment xml:lang="sr">Java бајтни кôд</comment>
  </mime-type>
  <mime-type type="application/x-compress">
    <comment>UNIX compressed file</comment>
    <comment xml:lang="sr">UNIX компресована датотека</comment>
    <magic priority="50">
      <match type="string" value="\037\235" offset="0"/>
    </magic>
    <glob pattern="*.Z"/>
  </mime-type>
  <mime-type type="application/x-compressed-tar">
    <comment>Gzipped Tar Archive</comment>
    <comment xml:lang="sr">Гзипована Тар архива</comment>
    <glob pattern="*.tar.gz"/>
    <glob pattern="*.tgz"/>
  </mime-type>
  <mime-type type="application/x-core">
    <comment>Program crash data</comment>
    <comment xml:lang="sr">Подаци о кркљавини програма</comment>
    <magic priority="50">
      <match type="string" mask="0xffffffff000000000000000000000000ff" value="\177ELF            \004" offset="0"/>
      <match type="string" value="\177ELF" offset="0">
        <match type="byte" value="1" offset="5">
          <match type="little16" value="4" offset="16"/>
        </match>
      </match>
      <match type="string" value="\177ELF" offset="0">
        <match type="byte" value="2" offset="5">
          <match type="big16" value="4" offset="16"/>
        </match>
      </match>
      <match type="string" value="Core\001" offset="0"/>
      <match type="string" value="Core\002" offset="0"/>
    </magic>
    <glob pattern="core"/>
  </mime-type>
  <mime-type type="application/x-cpio">
    <comment>CPIO archive</comment>
    <comment xml:lang="hu">CPIO-archívum</comment>
    <comment xml:lang="sr">CPIO архива</comment>
    <magic priority="50">
      <match type="host16" value="070707" offset="0"/>
      <match type="string" value="070701" offset="0"/>
      <match type="string" value="070702" offset="0"/>
      <match type="host16" value="0143561" offset="0"/>
    </magic>
    <glob pattern="*.cpio"/>
  </mime-type>
  <mime-type type="application/x-cpio-compressed">
    <comment>CPIO archive (gzip-compressed)</comment>
    <comment xml:lang="sr">CPIO архива (компресована gzip-ом)</comment>
    <glob pattern="*.cpio.gz"/>
  </mime-type>
  <mime-type type="application/x-csh">
    <comment>C shell script</comment>
    <comment xml:lang="hu">C shell-parancsfájl</comment>
    <comment xml:lang="sr">C скрипта окружења</comment>
  </mime-type>
  <mime-type type="application/x-dbase">
    <comment>dBASE document</comment>
    <comment xml:lang="sr">dBASE документ</comment>
    <glob pattern="*.dbf"/>
  </mime-type>
  <mime-type type="application/x-dbm">
    <magic priority="50">
      <match type="big32" value="0x061561" offset="0"/>
    </magic>
  </mime-type>
  <mime-type type="application/x-dc-rom">
    <comment>Dreamcast rom</comment>
    <comment xml:lang="sr">Dreamcast ром</comment>
    <glob pattern="*.dc"/>
  </mime-type>
  <mime-type type="application/x-deb">
    <comment>Debian package</comment>
    <comment xml:lang="hu">Debian-csomag</comment>
    <comment xml:lang="sr">Debian пакет</comment>
    <magic priority="50">
      <match type="string" value="!&lt;arch&gt;" offset="0">
        <match type="string" value="debian" offset="8"/>
      </match>
    </magic>
    <glob pattern="*.deb"/>
  </mime-type>
  <mime-type type="application/x-designer">
    <comment>Qt Designer File</comment>
    <comment xml:lang="sr">Qt Designer датотека</comment>
    <glob pattern="*.ui"/>
  </mime-type>
  <mime-type type="application/x-desktop">
    <comment>Desktop config file</comment>
    <comment xml:lang="sr">Датотека за подешавања радне површи</comment>
    <magic priority="50">
      <match type="string" value="[Desktop Entry]" offset="0:32"/>
      <match type="string" value="[Desktop Action" offset="0"/>
      <match type="string" value="[KDE Desktop Entry]" offset="0"/>
      <match type="string" value="# Config File" offset="0"/>
      <match type="string" value="# KDE Config File" offset="0"/>
    </magic>
    <glob pattern="*.desktop"/>
    <glob pattern="*.kdelnk"/>
  </mime-type>
  <mime-type type="application/x-dia-diagram">
    <comment>Dia diagram</comment>
    <comment xml:lang="hu">Dia-diagram</comment>
    <comment xml:lang="sr">Диа дијаграм</comment>
    <glob pattern="*.dia"/>
  </mime-type>
  <mime-type type="application/x-dvi">
    <comment>TeX Device Independent file</comment>
    <comment xml:lang="hu">TeX-eszközfüggetlenfájl (DVI)</comment>
    <comment xml:lang="sr">ТеХ датотека независна од уређаја (DVI)</comment>
    <magic priority="50">
      <match type="little16" value="0x02f7" offset="0"/>
    </magic>
    <glob pattern="*.dvi"/>
  </mime-type>
  <mime-type type="application/x-e-theme">
    <comment>Enlightenment theme</comment>
    <comment xml:lang="hu">Enlightenment-téma</comment>
    <comment xml:lang="sr">Enlightenment тема</comment>
    <glob pattern="*.etheme"/>
  </mime-type>
  <mime-type type="application/x-egon">
    <comment>Egon Animator</comment>
    <comment xml:lang="sr">Егон аниматор</comment>
    <glob pattern="*.egon"/>
  </mime-type>
  <mime-type type="application/x-executable">
    <comment>Executable</comment>
    <comment xml:lang="sr">Извршна</comment>
    <magic priority="40">
      <match type="string" value="\177ELF" offset="0">
        <match type="byte" value="1" offset="5">
          <match type="little16" value="2" offset="16"/>
        </match>
      </match>
      <match type="string" value="\177ELF" offset="0">
        <match type="byte" value="2" offset="5">
          <match type="big16" value="2" offset="16"/>
        </match>
      </match>
      <match type="string" value="MZ" offset="0"/>
      <match type="little16" value="0x521c" offset="0"/>
      <match type="host16" value="0420" offset="0"/>
      <match type="host16" value="0421" offset="0"/>
      <match type="little16" value="0603" offset="0"/>
    </magic>
    <glob pattern="*.exe"/>
  </mime-type>
  <mime-type type="application/x-font-type1">
    <comment>Fonts</comment>
    <comment xml:lang="hu">Betűkészletek</comment>
    <comment xml:lang="sr">Фонтови</comment>
    <magic priority="50">
      <match type="string" value="LWFN" offset="0"/>
      <match type="string" value="LWFN" offset="65"/>
      <match type="string" value="%!PS-AdobeFont-1." offset="0"/>
      <match type="string" value="%!PS-AdobeFont-1." offset="6"/>
      <match type="string" value="%!FontType1-1." offset="0"/>
      <match type="string" value="%!FontType1-1." offset="6"/>
    </magic>
    <glob pattern="*.pfa"/>
    <glob pattern="*.pfb"/>
    <glob pattern="*.gsf"/>
    <glob pattern="*.pcf.Z"/>
  </mime-type>
  <mime-type type="application/x-font-afm">
    <comment>Adobe font metrics</comment>
    <comment xml:lang="hu">Adobe-betűmetrika</comment>
    <comment xml:lang="sr">Adobe метрика фонта</comment>
    <glob pattern="*.afm"/>
  </mime-type>
  <mime-type type="application/x-font-bdf">
    <comment>BDF font</comment>
    <comment xml:lang="hu">BDF-betűkészlet</comment>
    <comment xml:lang="sr">BDF фонт</comment>
    <magic priority="50">
      <match type="string" value="STARTFONT\040" offset="0"/>
    </magic>
    <glob pattern="*.bdf"/>
  </mime-type>
  <mime-type type="application/x-font-dos">
    <comment>DOS font</comment>
    <comment xml:lang="hu">DOS-betűkészlet</comment>
    <comment xml:lang="sr">DOS фонт</comment>
    <magic priority="50">
      <match type="string" value="\xff\x46\x4f\x4e" offset="0"/>
      <match type="string" value="\x00\x45\x47\x41" offset="7"/>
      <match type="string" value="\x00\x56\x49\x44" offset="7"/>
    </magic>
  </mime-type>
  <mime-type type="application/x-font-framemaker">
    <comment>Adobe FrameMaker font</comment>
    <comment xml:lang="hu">Adobe FrameMaker-betűkészlet</comment>
    <comment xml:lang="sr">Adobe FrameMaker фонт</comment>
    <magic priority="50">
      <match type="string" value="&lt;MakerScreenFont" offset="0"/>
    </magic>
  </mime-type>
  <mime-type type="application/x-font-libgrx">
    <comment>LIBGRX font</comment>
    <comment xml:lang="hu">LIBGRX-betűkészlet</comment>
    <comment xml:lang="sr">LIBGRX фонт</comment>
    <magic priority="50">
      <match type="string" value="\x14\x02\x59\x19" offset="0"/>
    </magic>
  </mime-type>
  <mime-type type="application/x-font-linux-psf">
    <comment>Linux PSF console font</comment>
    <comment xml:lang="hu">Linux PSF konzolos betűkészlet</comment>
    <comment xml:lang="sr">Линукс PSF конзолни фонт</comment>
    <magic priority="50">
      <match type="string" value="\x36\x04" offset="0"/>
    </magic>
    <glob pattern="*.psf"/>
  </mime-type>
  <mime-type type="application/x-font-pcf">
    <comment>PCF font</comment>
    <comment xml:lang="hu">PCF-betűkészlet</comment>
    <comment xml:lang="sr">PCF фонт</comment>
    <magic priority="50">
      <match type="string" value="\001fcp" offset="0"/>
    </magic>
    <glob pattern="*.pcf"/>
  </mime-type>
  <mime-type type="application/x-font-otf">
    <comment>OpenType font</comment>
    <comment xml:lang="hu">OpenType-betűkészlet</comment>
    <comment xml:lang="sr">OpenType фонт</comment>
    <magic priority="50">
      <match type="string" value="OTTO" offset="0"/>
    </magic>
  </mime-type>
  <mime-type type="application/x-font-speedo">
    <comment>Speedo font</comment>
    <comment xml:lang="hu">Speedo-betűkészlet</comment>
    <comment xml:lang="sr">Speedo фонт</comment>
    <magic priority="50">
      <match type="string" value="D1.0\015" offset="0"/>
    </magic>
    <glob pattern="*.spd"/>
  </mime-type>
  <mime-type type="application/x-font-sunos-news">
    <comment>SunOS News font</comment>
    <comment xml:lang="hu">SunOS News-betűkészlet</comment>
    <comment xml:lang="sr">SunOS News фонт</comment>
    <magic priority="50">
      <match type="string" value="StartFont" offset="0"/>
      <match type="string" value="\x13\x7A\x29" offset="0"/>
      <match type="string" value="\x13\x7A\x2B" offset="8"/>
    </magic>
  </mime-type>
  <mime-type type="application/x-font-tex">
    <comment>TeX font</comment>
    <comment xml:lang="hu">TeX-betűkészlet</comment>
    <comment xml:lang="sr">ТеХ фонт</comment>
    <magic priority="50">
      <match type="string" value="\367\203" offset="0"/>
      <match type="string" value="\367\131" offset="0"/>
      <match type="string" value="\367\312" offset="0"/>
    </magic>
  </mime-type>
  <mime-type type="application/x-font-tex-tfm">